"""add signup route support, phone/building fields

Revision ID: 468c3a774c85
Revises: b683828300f4
Create Date: 2026-09-07 14:48:43.833317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468c3a774c85'
down_revision = 'b683828300f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('building', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('building')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
